package com.frostre1997.droidutility

enum class BloatCategory {
    OEM_BLOATWARE,
    CARRIER_APPS,
    SOCIAL_MEDIA,
    GAMES,
    PRODUCTIVITY_BLOAT,
    TRACKING_SPYWARE,
    ADVERTISING,
    CLOUD_SERVICES,
    REDUNDANT_APPS,
    PRIVACY_CONCERNING
}

enum class BloatRisk {
    SAFE,
    CAUTION,
    ADVANCED
}

data class BloatApp(
    val packageName: String,
    val name: String,
    val description: String,
    val category: BloatCategory,
    val risk: BloatRisk = BloatRisk.SAFE,
    val alternatives: String = ""
)

object BloatList {

    val SAMSUNG_BLOATWARE = listOf(
        BloatApp("com.samsung.android.app.spage", "Samsung Free", "News and content aggregator", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.app.routines", "Bixby Routines", "Automation app (keep if used)", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.samsung.android.bixby.wakeup", "Bixby Voice Wakeup", "Bixby voice activation", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.bixby.service", "Bixby Service", "Bixby assistant service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.bixby.agent", "Bixby Agent", "Bixby integration", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.bixbyvision.framework", "Bixby Vision", "AR features", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.aremoji", "AR Emoji", "Animated emoji", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.sec.android.app.sbrowser", "Samsung Internet", "Stock browser", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Chrome, Firefox, Brave"),
        BloatApp("com.samsung.android.app.dressroom", "Samsung Decor", "Wallpaper service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.scloud", "Samsung Cloud", "Cloud backup", BloatCategory.CLOUD_SERVICES, BloatRisk.CAUTION),
        BloatApp("com.samsung.android.sdk.handwriting", "Handwriting SDK", "SDK for handwriting", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.mateagent", "Samsung Friends", "Social gaming platform", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.app.earmark", "Samsung Earmark", "Audio service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.fmm", "Find My Mobile", "Device tracking", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.samsung.android.kidsinstaller", "Kids Mode", "Kids interface", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.app.storyalbumwidget", "Story Album", "Photo albums", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.service.travel", "Samsung Travel", "Travel service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.tripadvisor.tripadvisor", "TripAdvisor", "Travel app", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.app.settings.bixby", "Bixby Settings", "Bixby configuration", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.app.appsedge", "Apps Edge", "Edge panel", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.app.cocktailbarservice", "Edge Panels", "Edge panel service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.personalpage.service", "Secure Folder", "Private folder", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.samsung.android.samsungpass", "Samsung Pass", "Password manager", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.samsung.android.spay", "Samsung Pay", "Payment service", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.samsung.android.spayfw", "Samsung Pay Framework", "Payment framework", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.email.provider", "Samsung Email", "Email client", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Gmail, Outlook"),
        BloatApp("com.samsung.android.app.notes", "Samsung Notes", "Note taking app", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION, "Google Keep, Notion"),
        BloatApp("com.samsung.android.calendar", "Samsung Calendar", "Calendar app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Google Calendar"),
        BloatApp("com.dsi.ant.sample.acquirechannels", "ANT+ Plugins", "ANT radio service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.dsi.ant.service.socket", "ANT+ Service", "ANT connectivity", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.dsi.ant.server", "ANT+ Server", "ANT background service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.game.gamehome", "Game Launcher", "Game management", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.enhance.gameservice", "Game Optimizing Service", "Game optimization", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.game.gametools", "Game Tools", "Game utilities", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.hmt.vrsvc", "Gear VR Service", "VR service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.hmt.vrshell", "Gear VR Shell", "VR interface", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.weather", "Samsung Weather", "Weather app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Google Weather"),
        BloatApp("com.sec.android.daemonapp", "Weather Daemon", "Weather service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.drivelink.stub", "Car Mode", "Car interface", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.app.galaxyfinder", "Galaxy Apps", "Samsung app store", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.sec.android.app.shealth", "Samsung Health", "Health tracking", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION, "Google Fit"),
        BloatApp("com.samsung.android.app.watchmanagerstub", "Galaxy Wearable", "Watch companion", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.samsung.android.provider.stickerprovider", "Sticker Center", "Sticker provider", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.stickercenter", "Sticker Center", "Sticker management", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.authfw", "Authentication Framework", "Biometric auth", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.samsung.android.camera.fastmotion", "Fast Motion Camera", "Slow-mo camera mode", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.mdm", "MDM App", "Enterprise management", BloatCategory.OEM_BLOATWARE, BloatRisk.ADVANCED),
        BloatApp("com.samsung.android.sdk.professionalaudio.utility.jammonitor", "Professional Audio SDK", "Audio SDK", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.sec.enterprise.knox.attestation", "Knox Attestation", "Enterprise security", BloatCategory.OEM_BLOATWARE, BloatRisk.ADVANCED),
        BloatApp("com.sec.enterprise.knox.cloudmdm.sso", "Knox Cloud MDM", "Enterprise management", BloatCategory.OEM_BLOATWARE, BloatRisk.ADVANCED),
        BloatApp("com.samsung.android.knox.containeragent", "Knox Container", "Enterprise container", BloatCategory.OEM_BLOATWARE, BloatRisk.ADVANCED)
    )

    val XIAOMI_BLOATWARE = listOf(
        BloatApp("com.miui.msa.global", "MIUI System Ad Solution", "Ad service", BloatCategory.ADVERTISING),
        BloatApp("com.miui.analytics", "MIUI Analytics", "Usage analytics", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.miui.bugreport", "MIUI Bug Report", "Bug reporting", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.miui.cleanmaster", "MIUI Cleaner", "System cleaner", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "SD Maid"),
        BloatApp("com.miui.player", "MIUI Music", "Music player", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Poweramp, Musicolet"),
        BloatApp("com.miui.video", "MIUI Video", "Video player", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "VLC, MX Player"),
        BloatApp("com.miui.notes", "MIUI Notes", "Note app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Google Keep"),
        BloatApp("com.miui.calculator", "MIUI Calculator", "Calculator", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Google Calculator"),
        BloatApp("com.miui.gallery", "MIUI Gallery", "Gallery app", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION, "Google Photos"),
        BloatApp("com.miui.micloudservice", "Mi Cloud", "Cloud service", BloatCategory.CLOUD_SERVICES, BloatRisk.CAUTION),
        BloatApp("com.miui.cloudbackup", "Mi Cloud Backup", "Cloud backup", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.miui.cloudservice", "Mi Cloud Service", "Cloud sync", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.miui.yellowpage", "Yellow Pages", "Business directory", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.miui.touchassistant", "Touch Assistant", "Floating button", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.miui.voiceassist", "Mi Voice", "Voice assistant", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.xiaomi.glgm", "Xiaomi Game Center", "Game store", BloatCategory.GAMES),
        BloatApp("com.xiaomi.joyose", "Joyose", "Game optimization", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.xiaomi.payment", "Mi Pay", "Payment service", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.xiaomi.midrop", "Mi Drop", "File sharing", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "ShareIt"),
        BloatApp("com.xiaomi.finddevice", "Find Device", "Device tracking", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.xiaomi.xmseller", "Mi Sell", "App recommendations", BloatCategory.ADVERTISING),
        BloatApp("com.xiaomi.mipicks", "Mi Picks", "App store", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.xiaomi.scanner", "Mi Scanner", "Document scanner", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Google Lens"),
        BloatApp("com.xiaomi.mirecycle", "Mi Recycle", "Recycle reminder", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.xiaomi.mircs", "Mi RCS", "Messaging service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.mipay.wallet.in", "Mi Wallet", "Digital wallet", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.miui.huanji", "Mi Mover", "Device migration", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.miui.wmsvc", "Wearable Service", "Wearable sync", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.xiaomi.discover", "Mi Browser", "Stock browser", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Chrome, Firefox"),
        BloatApp("com.miui.face", "MIUI Face", "Face unlock", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.miui.hybrid.accessory", "Mi Home", "Smart home", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.miui.accessibility", "MIUI Accessibility", "Accessibility service", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.xiaomi.mtb", "Mi Travel", "Travel service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.xiaomi.mircs", "Mi RCS Service", "Rich messaging", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.miui.contentextension", "Content Extension", "Smart text", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.miui.screenrecorder", "Screen Recorder", "Screen capture", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.miui.fm", "MIUI FM Radio", "FM radio", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.miui.compass", "MIUI Compass", "Compass app", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.caf.fmradio", "FM Radio", "Radio service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.miui.weather2", "MIUI Weather", "Weather app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.miui.notes", "Mi Notes", "Note taking", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.xiaomi.bluetooth", "Mi Bluetooth", "Bluetooth service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.xiaomi.bluetooth.headset", "Mi Headset", "Headset service", BloatCategory.OEM_BLOATWARE)
    )

    val ONEPLUS_BLOATWARE = listOf(
        BloatApp("net.oneplus.forums", "OnePlus Community", "Community forum", BloatCategory.OEM_BLOATWARE),
        BloatApp("net.oneplus.weather", "OnePlus Weather", "Weather app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("net.oneplus.filemanager", "OnePlus File Manager", "File manager", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Files by Google"),
        BloatApp("net.oneplus.gallery", "OnePlus Gallery", "Gallery app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Google Photos"),
        BloatApp("com.oneplus.backuprestore", "OnePlus Backup", "Backup service", BloatCategory.CLOUD_SERVICES, BloatRisk.CAUTION),
        BloatApp("com.oneplus.bbs", "OnePlus Community", "User forum", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oneplus.camera", "OnePlus Camera", "Camera app", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION, "Google Camera"),
        BloatApp("com.oneplus.cloud", "OnePlus Cloud", "Cloud service", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.oneplus.filemanager", "File Manager", "File explorer", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.oneplus.instant.translation", "Instant Translation", "Translation service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oneplus.note", "OnePlus Notes", "Note app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.oneplus.opdpservice", "DPS Service", "Audio processing", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oneplus.screenshot", "Screenshot", "Screen capture", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oneplus.soundrecorder", "Sound Recorder", "Voice recorder", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.oneplus.twodbrowser", "TwoD Browser", "Web browser", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oneplus.camera.facebeautify", "Face Beautify", "Camera filter", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oneplus.gamespace", "Game Space", "Game launcher", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.oneplus.healthcheck", "Health Check", "System health", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oneplus.picturestore", "Picture Store", "Photo backup", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.oneplus.push", "OnePlus Push", "Push notifications", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oneplus.scan", "OnePlus Scanner", "QR scanner", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.oneplus.setupwizard", "Setup Wizard", "Initial setup", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oneplus.skin", "OnePlus Skin", "Theme engine", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oem.logkitsdservice", "LogKit Service", "Logging service", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.oem.oemlogkit", "OEM LogKit", "Diagnostic logging", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.oneplus.card", "OnePlus Cards", "Cards app", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oneplus.deskclock", "OnePlus Clock", "Clock app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.oneplus.music", "OnePlus Music", "Music player", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.oneplus.music2", "OnePlus Music 2", "Music player", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.oneplus.voice.recorder", "Voice Recorder", "Audio recorder", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE)
    )

    val HUAWEI_BLOATWARE = listOf(
        BloatApp("com.huawei.android.totemweather", "Huawei Weather", "Weather app", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.android.airsharing", "Huawei Share", "File sharing", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.android.chr", "Huawei CHR", "Crash reporting", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.huawei.appmarket", "Huawei AppGallery", "App store", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.browser", "Huawei Browser", "Web browser", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.huawei.browserhomepage", "Huawei Browser Home", "Browser homepage", BloatCategory.ADVERTISING),
        BloatApp("com.huawei.contactscamcard", "Business Cards", "Contact cards", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.desktop.explorer", "Desktop Mode", "Desktop interface", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.hwread.alarm", "Huawei Reader", "E-reader", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.hwvoip", "Huawei VoIP", "VoIP service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.iaware", "Intelligent Awareness", "Usage tracking", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.huawei.livewallpaper.nature", "Nature Wallpaper", "Live wallpaper", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.mirror", "Huawei Mirror", "Mirror app", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.music", "Huawei Music", "Music player", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.huawei.notepad", "Huawei Notepad", "Note app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.huawei.phoneservice", "Phone Services", "Device services", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.huawei.rcsserviceapplication", "RCS Service", "Messaging service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.recsys", "Recommendation System", "App suggestions", BloatCategory.ADVERTISING),
        BloatApp("com.huawei.scanner", "Huawei Scanner", "QR scanner", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.huawei.search", "Huawei Search", "System search", BloatCategory.ADVERTISING),
        BloatApp("com.huawei.videoeditor", "Video Editor", "Video editing", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.huawei.videoplayer", "Huawei Video", "Video player", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.huawei.wallet", "Huawei Wallet", "Digital wallet", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.watch.sync", "Watch Sync", "Wearable sync", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.welink", "WeLink", "Enterprise messaging", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.himovie.overseas", "Huawei Video", "Video streaming", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.hwid", "Huawei ID", "Account service", BloatCategory.CLOUD_SERVICES, BloatRisk.CAUTION),
        BloatApp("com.huawei.gameassistant", "Game Assistant", "Game optimization", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.gamebox", "Game Center", "Game store", BloatCategory.GAMES),
        BloatApp("com.huawei.health", "Huawei Health", "Health tracking", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.huawei.hiaction", "HiAction", "Gesture control", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.hiboard", "HiBoard", "Notification panel", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.hicamera", "HiCamera", "Camera service", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.huawei.hivoice", "HiVoice", "Voice assistant", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.hiviewt", "HiView", "Display service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.hwasm", "App Manager", "App management", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.hwdetectrepair", "Diagnostics", "Device diagnostics", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.hff", "Huawei Fit", "Fitness app", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.hwfoundation", "Foundation", "Core services", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.huawei.login", "Huawei Login", "Account service", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.huawei.KoBackup", "KoBackup", "Backup service", BloatCategory.CLOUD_SERVICES, BloatRisk.CAUTION),
        BloatApp("com.huawei.android.launcher", "Huawei Launcher", "Home launcher", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION, "Nova Launcher"),
        BloatApp("com.huawei.screenrecorder", "Screen Recorder", "Screen capture", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.huawei.storyalbum", "Story Album", "Photo albums", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.synergy", "Huawei Share", "Device sharing", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.tips", "Huawei Tips", "Tips and tricks", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.android.instantshare", "Instant Share", "Quick sharing", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.arengine.service", "AR Engine", "Augmented reality", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.bluetooth", "Huawei Bluetooth", "Bluetooth service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.contacts", "Huawei Contacts", "Contact manager", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.huawei.hwcallrecorder", "Call Recorder", "Call recording", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.huawei.hwdiskmode", "Disk Mode", "USB mode", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.huawei.mms", "Huawei Messages", "Messaging app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.huawei.ringtone", "Huawei Ringtones", "Ringtone picker", BloatCategory.OEM_BLOATWARE)
    )

    val OPPO_BLOATWARE = listOf(
        BloatApp("com.coloros.backuprestore", "OPPO Backup", "Backup service", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.coloros.browserservice", "OPPO Browser Service", "Browser service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.coloros.childrenspace", "Kids Space", "Kids mode", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.coloros.cloud", "OPPO Cloud", "Cloud storage", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.coloros.findmyphone", "Find My Phone", "Device tracking", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.coloros.gamespace", "Game Space", "Game launcher", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.coloros.healthcheck", "Health Check", "System health", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.coloros.music", "OPPO Music", "Music player", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.coloros.oppomultiapp", "App Cloner", "Dual apps", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.coloros.phonemanager", "Phone Manager", "Device manager", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.coloros.phonenoareainquire", "Region Check", "Regional service", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.coloros.scene", "Smart Scene", "Context awareness", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.coloros.screenrecorder", "Screen Recorder", "Screen capture", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.coloros.securepay", "Secure Payment", "Payment security", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.coloros.speechassist", "Voice Assistant", "Voice assistant", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.coloros.translate.engine", "Translation", "Translation service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.coloros.video", "OPPO Video", "Video player", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.coloros.weather2", "OPPO Weather", "Weather app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.coloros.widget", "OPPO Widgets", "Widget provider", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oppo.community", "OPPO Community", "User forum", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oppo.feedback", "OPPO Feedback", "User feedback", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oppo.market", "OPPO App Market", "App store", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oppo.music", "OPPO Music", "Music player", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.oppo.ocr", "OCR Service", "Text recognition", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oppo.osie.karaokeservice", "Karaoke Service", "Karaoke feature", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oppo.ovoicemaker", "Voice Maker", "Voice effects", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oppo.plusservice", "OPPO+ Service", "Premium service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oppo.quicksearchbox", "Quick Search", "Search app", BloatCategory.ADVERTISING),
        BloatApp("com.oppo.screensaver", "Screensaver", "Daydream mode", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oppo.soundrecorder", "Sound Recorder", "Voice recorder", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.oppo.usercenter", "User Center", "Account service", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.nearme.browser", "OPPO Browser", "Web browser", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.nearme.statistics.rom", "Statistics", "Usage tracking", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.nearme.themestore", "Theme Store", "Theme marketplace", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.heytap.browser", "HeyTap Browser", "Web browser", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.heytap.cloud", "HeyTap Cloud", "Cloud service", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.heytap.habit", "HeyTap Habit", "Usage habits", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.heytap.market", "HeyTap Store", "App store", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.heytap.mcs", "HeyTap Push", "Push service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.heytap.openid", "HeyTap ID", "Account service", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.heytap.pictorial", "HeyTap Wallpaper", "Wallpaper service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.heytap.sport", "HeyTap Health", "Health tracking", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.heytap.usercenter", "HeyTap Account", "Account manager", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.oppo.logkitservice", "LogKit", "Diagnostic logging", BloatCategory.TRACKING_SPYWARE)
    )

    val VIVO_BLOATWARE = listOf(
        BloatApp("com.vivo.abe", "Vivo ABE", "App backup", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.vivo.agent", "Vivo Agent", "Assistant", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.appfilter", "App Filter", "App management", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.appmanager", "App Manager", "Package manager", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.appstore", "Vivo App Store", "App marketplace", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.browser", "Vivo Browser", "Web browser", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.vivo.calculator", "Vivo Calculator", "Calculator", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.vivo.cloud", "Vivo Cloud", "Cloud storage", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.vivo.dream.camera", "Dream Camera", "Camera effects", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.dream.music", "Dream Music", "Music player", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.vivo.dream.videocall", "Video Call", "Video calling", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.dts.dtsvisualizer", "DTS Visualizer", "Audio effects", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.email", "Vivo Email", "Email client", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.vivo.facebeauty", "Face Beauty", "Camera filter", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.findphone", "Find Phone", "Device tracking", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.vivo.game", "Vivo Game", "Game launcher", BloatCategory.GAMES),
        BloatApp("com.vivo.gamelog", "Game Log", "Game tracking", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.vivo.gamewatch", "Game Watch", "Game monitoring", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.hybrid", "Hybrid", "System features", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.ise", "iService", "Device service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.mirror", "Vivo Mirror", "Mirror app", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.multiapp", "App Cloner", "Dual apps", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.vivo.nightscene", "Night Scene", "Night mode", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.noiseoff", "Noise Off", "Noise cancellation", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.notes", "Vivo Notes", "Note app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.vivo.oupload", "Easy Share", "File sharing", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.pureview", "Pure View", "Display service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.scanner", "Vivo Scanner", "QR scanner", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.vivo.simplestyle", "Simple Mode", "Easy mode", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.smartmultiwindow", "Smart Window", "Split screen", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.smartseat", "Smart Seat", "Smart features", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.tipserver", "Tips", "Tips service", BloatCategory.ADVERTISING),
        BloatApp("com.vivo.tws", "TWS Service", "Earbuds service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.upslide", "Up Slide", "Navigation", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.video", "Vivo Video", "Video player", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.vivo.vivobrowser", "Vivo Browser", "Web browser", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.vivo.vivotalk", "Vivo Talk", "Voice assistant", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.vivo.weather", "Vivo Weather", "Weather app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.vivo.widget", "Vivo Widgets", "Widget provider", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.bbk.account", "BBK Account", "Account service", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.bbk.theme", "BBK Theme", "Theme store", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.iqoo.engine", "iQOO Engine", "Game engine", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.iqoo.scene", "iQOO Scene", "Game scene", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.mobiletools.systemhelper", "System Helper", "System optimization", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.dataplatform", "Data Platform", "Analytics", BloatCategory.TRACKING_SPYWARE)
    )

    val REALME_BLOATWARE = listOf(
        BloatApp("com.realme.link", "realme Link", "IoT service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.realme.logtool", "Log Tool", "Diagnostic logging", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.realme.mech", "realme Mech", "Game features", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.realme.securitycheck", "Security Check", "App verification", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.realme.ui", "realme UI", "System UI", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.heytap.browser", "HeyTap Browser", "Web browser", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.heytap.cloud", "HeyTap Cloud", "Cloud service", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.heytap.habit", "HeyTap Habit", "Usage analytics", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.heytap.market", "HeyTap Store", "App store", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.heytap.mcs", "HeyTap Push", "Push notifications", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.heytap.openid", "HeyTap ID", "Account service", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.heytap.pictorial", "HeyTap Wallpaper", "Wallpaper", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.heytap.sport", "HeyTap Health", "Health tracking", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.heytap.usercenter", "HeyTap Account", "Account manager", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.coloros.gamespace", "Game Space", "Game launcher", BloatCategory.GAMES),
        BloatApp("com.coloros.screenrecorder", "Screen Recorder", "Screen capture", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.coloros.weather2", "Weather", "Weather app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.coloros.backuprestore", "Backup", "Backup service", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.coloros.cloud", "Cloud", "Cloud storage", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.coloros.findmyphone", "Find My Phone", "Device tracking", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.coloros.healthcheck", "Health Check", "System diagnostics", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.coloros.music", "Music", "Music player", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.coloros.oppomultiapp", "App Cloner", "Dual apps", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.coloros.phonemanager", "Phone Manager", "Device manager", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.coloros.securepay", "Secure Payment", "Payment security", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.coloros.speechassist", "Voice Assistant", "Voice assistant", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.coloros.video", "Video", "Video player", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.nearme.statistics.rom", "Statistics", "Usage tracking", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.oppo.logkitservice", "LogKit", "Diagnostic logging", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.oppo.market", "App Market", "App store", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.oppo.quicksearchbox", "Quick Search", "Search app", BloatCategory.ADVERTISING)
    )

    val MOTOROLA_BLOATWARE = listOf(
        BloatApp("com.motorola.demomode", "Demo Mode", "Retail mode", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.motorola.email", "Motorola Email", "Email client", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.motorola.face", "Moto Face", "Face unlock", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.motorola.gamemode", "Moto Gametime", "Game launcher", BloatCategory.GAMES),
        BloatApp("com.motorola.help", "Moto Help", "Help app", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.motorola.motocare", "Moto Care", "Device care", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.motorola.moto", "Moto App", "Moto features", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.motorola.motosignature.app", "Moto Signature", "App signature", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.motorola.timeweatherwidget", "Weather Widget", "Weather widget", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.motorola.visualvoicemail", "Visual Voicemail", "Voicemail app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.motorola.genie", "Moto Guide", "Setup guide", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.motorola.motodisplay", "Moto Display", "Always-on display", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.motorola.bach", "Moto Actions", "Gesture control", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.motorola.brapps", "BR Apps", "Regional apps", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.motorola.fmradio", "FM Radio", "Radio app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.motorola.ccc.ota", "OTA Update", "System updates", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.motorola.ccc.mainplancur", "Main Plan", "Carrier service", BloatCategory.CARRIER_APPS),
        BloatApp("com.motorola.comcast.settings", "Comcast Settings", "Carrier settings", BloatCategory.CARRIER_APPS),
        BloatApp("com.motorola.ccc.checkin", "Checkin", "Device check-in", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.motorola.slpc_sys", "SLPC System", "Location service", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.motorola.camera2", "Moto Camera", "Camera app", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION, "Google Camera"),
        BloatApp("com.motorola.camera3", "Moto Camera 3", "Camera app", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION, "Google Camera"),
        BloatApp("com.motorola.soundrecorder", "Sound Recorder", "Voice recorder", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.motorola.gallery", "Moto Gallery", "Photo gallery", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Google Photos"),
        BloatApp("com.motorola.filemanager", "File Manager", "File explorer", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Files by Google")
    )

    val GOOGLE_BLOATWARE = listOf(
        BloatApp("com.google.android.apps.wellbeing", "Digital Wellbeing", "Screen time tracker", BloatCategory.TRACKING_SPYWARE, BloatRisk.CAUTION),
        BloatApp("com.google.android.apps.tachyon", "Google Duo", "Video calling", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "WhatsApp, Telegram"),
        BloatApp("com.google.android.apps.messaging", "Google Messages", "SMS app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Textra, Signal"),
        BloatApp("com.google.android.dialer", "Google Phone", "Dialer app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "True Dialer"),
        BloatApp("com.google.android.contacts", "Google Contacts", "Contact manager", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.google.android.deskclock", "Google Clock", "Clock app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.google.android.calendar", "Google Calendar", "Calendar", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.google.android.keep", "Google Keep", "Note taking", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Notion, Obsidian"),
        BloatApp("com.google.android.apps.docs.editors.docs", "Google Docs", "Document editor", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.google.android.apps.docs.editors.sheets", "Google Sheets", "Spreadsheet", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.google.android.apps.docs.editors.slides", "Google Slides", "Presentation", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.google.android.apps.maps", "Google Maps", "Navigation", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION, "Organic Maps"),
        BloatApp("com.google.android.youtube", "YouTube", "Video streaming", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION, "NewPipe, Invidious"),
        BloatApp("com.google.android.apps.youtube.music", "YouTube Music", "Music streaming", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "Spotify, Apple Music"),
        BloatApp("com.google.android.videos", "Google TV", "Movie store", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.google.android.apps.photos", "Google Photos", "Photo backup", BloatCategory.CLOUD_SERVICES, BloatRisk.CAUTION),
        BloatApp("com.google.android.apps.drive", "Google Drive", "Cloud storage", BloatCategory.CLOUD_SERVICES, BloatRisk.CAUTION, "Nextcloud"),
        BloatApp("com.google.android.music", "Google Play Music", "Music player", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.google.android.vending", "Play Store", "App store", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION, "F-Droid, Aurora Store"),
        BloatApp("com.google.android.gms", "Google Play Services", "Core services", BloatCategory.TRACKING_SPYWARE, BloatRisk.ADVANCED, "microG"),
        BloatApp("com.google.android.gsf", "Google Services Framework", "Service framework", BloatCategory.TRACKING_SPYWARE, BloatRisk.ADVANCED),
        BloatApp("com.google.android.backuptransport", "Google Backup", "Backup service", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.google.android.syncadapters.contacts", "Contact Sync", "Contact syncing", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.google.android.syncadapters.calendar", "Calendar Sync", "Calendar syncing", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.google.android.ondevicepersonalization", "On-Device AI", "Local AI", BloatCategory.PRIVACY_CONCERNING, BloatRisk.CAUTION),
        BloatApp("com.google.android.as", "Google Assistant", "Voice assistant", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.google.android.googlequicksearchbox", "Google App", "Search assistant", BloatCategory.TRACKING_SPYWARE, BloatRisk.CAUTION, "DuckDuckGo"),
        BloatApp("com.google.android.tts", "Google TTS", "Text-to-speech", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "eSpeak"),
        BloatApp("com.google.android.inputmethod.latin", "Gboard", "Keyboard", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "OpenBoard, FlorisBoard"),
        BloatApp("com.google.android.apps.inputmethod.hindi", "Google Hindi Input", "Hindi keyboard", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.google.android.apps.inputmethod.zhuyin", "Zhuyin Input", "Chinese keyboard", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.google.android.apps.inputmethod.pinyin", "Pinyin Input", "Chinese keyboard", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.google.android.apps.fitness", "Google Fit", "Fitness tracking", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE, "OpenTracks"),
        BloatApp("com.google.android.apps.nbu.paisa.user", "Google Pay", "Payment app", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.google.android.apps.walletnfcrel", "Google Wallet", "Digital wallet", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.google.android.apps.subscriptions.red", "Google One", "Subscription manager", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.google.android.apps.magicservice", "Magic Service", "Device service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.google.android.marvin.talkback", "TalkBack", "Screen reader", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.google.android.feedback", "Google Feedback", "Crash reporting", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.google.android.onetimeinitializer", "One Time Init", "Setup wizard", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.google.android.partnersetup", "Partner Setup", "Carrier setup", BloatCategory.CARRIER_APPS),
        BloatApp("com.google.android.setupwizard", "Setup Wizard", "Initial setup", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.google.android.printservice.recommendation", "Print Service", "Printer discovery", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.google.android.overlay.gmsgsaconfig", "GMS Config", "Service overlay", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.google.android.configupdater", "Config Updater", "Config updates", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.google.ar.core", "ARCore", "Augmented reality", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.google.android.apps.miphone.aiai", "AI Features", "On-device AI", BloatCategory.PRIVACY_CONCERNING),
        BloatApp("com.google.android.gms.integrity", "Play Integrity", "App verification", BloatCategory.TRACKING_SPYWARE, BloatRisk.ADVANCED),
        BloatApp("com.google.mainline.telemetry", "Telemetry", "Usage analytics", BloatCategory.TRACKING_SPYWARE, BloatRisk.ADVANCED),
        BloatApp("com.google.mainline.adservices", "Ad Services", "Advertising ID", BloatCategory.ADVERTISING, BloatRisk.ADVANCED)
    )

    val CARRIER_BLOATWARE = listOf(
        BloatApp("com.att.csoh.mobile", "AT&T Mobile Security", "Security app", BloatCategory.CARRIER_APPS),
        BloatApp("com.att.callprotect", "AT&T Call Protect", "Spam filter", BloatCategory.CARRIER_APPS),
        BloatApp("com.att.myWireless", "AT&T My Wireless", "Account app", BloatCategory.CARRIER_APPS),
        BloatApp("com.att.tv", "AT&T TV", "Streaming service", BloatCategory.CARRIER_APPS),
        BloatApp("com.samsung.attvvm", "AT&T Voicemail", "Voicemail app", BloatCategory.CARRIER_APPS),
        BloatApp("com.att.android.attsmartwifi", "AT&T Smart WiFi", "WiFi manager", BloatCategory.CARRIER_APPS),
        BloatApp("com.att.dh", "AT&T Device Help", "Device support", BloatCategory.CARRIER_APPS),
        BloatApp("com.att.dtv", "DIRECTV", "Streaming app", BloatCategory.CARRIER_APPS),
        BloatApp("com.att.iqi", "AT&T IQI", "Network analytics", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.att.android.mobile.attmessages", "AT&T Messages", "Messaging app", BloatCategory.CARRIER_APPS),
        BloatApp("com.att.facetime", "AT&T FaceTime", "Carrier services", BloatCategory.CARRIER_APPS),
        BloatApp("com.verizon.mips.services", "Verizon Services", "Carrier services", BloatCategory.CARRIER_APPS),
        BloatApp("com.verizon.obdm_permissions", "Verizon ODM", "Device management", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.verizon.loginengine.unbranded", "Verizon Login", "Account service", BloatCategory.CARRIER_APPS),
        BloatApp("com.verizon.vzwavs", "Verizon AVS", "Video service", BloatCategory.CARRIER_APPS),
        BloatApp("com.vzw.hss.myverizon", "My Verizon", "Account app", BloatCategory.CARRIER_APPS),
        BloatApp("com.vznavigator.Generic", "VZ Navigator", "Navigation", BloatCategory.CARRIER_APPS),
        BloatApp("com.vcast.mediamanager", "Verizon Media Manager", "Media sync", BloatCategory.CARRIER_APPS),
        BloatApp("com.asurion.android.protech.att", "AT&T ProTech", "Tech support", BloatCategory.CARRIER_APPS),
        BloatApp("com.asurion.android.verizon.vms", "Verizon Support", "Tech support", BloatCategory.CARRIER_APPS),
        BloatApp("com.sprint.w.installer", "Sprint ID", "Sprint installer", BloatCategory.CARRIER_APPS),
        BloatApp("com.sprint.zone", "Sprint Zone", "Sprint app", BloatCategory.CARRIER_APPS),
        BloatApp("com.sprint.ms.smf.services", "Sprint Services", "Sprint backend", BloatCategory.CARRIER_APPS),
        BloatApp("com.sprint.fpremium", "Sprint Fun & Games", "Games portal", BloatCategory.GAMES),
        BloatApp("com.sprint.ecid", "Sprint CID", "Caller ID", BloatCategory.CARRIER_APPS),
        BloatApp("com.tmobile.pr.adapt", "T-Mobile Adapt", "Adaptive services", BloatCategory.CARRIER_APPS),
        BloatApp("com.tmobile.pr.mytmobile", "T-Mobile App", "Account app", BloatCategory.CARRIER_APPS),
        BloatApp("com.tmobile.services.nameid", "T-Mobile Name ID", "Caller ID", BloatCategory.CARRIER_APPS),
        BloatApp("com.tmobile.echolocator", "T-Mobile Echo", "Location service", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.tmobile.tmlab", "T-Mobile LAB", "Experimental features", BloatCategory.CARRIER_APPS),
        BloatApp("com.tmobile.m1", "T-Mobile M1", "Messaging", BloatCategory.CARRIER_APPS),
        BloatApp("com.tmobile.rsuadapter", "T-Mobile RSU", "SIM services", BloatCategory.CARRIER_APPS),
        BloatApp("com.tmobile.uscctriggerappinstaller", "USCC App Installer", "App installer", BloatCategory.CARRIER_APPS),
        BloatApp("com.uscc.thememgr", "USCC Theme", "Theme manager", BloatCategory.CARRIER_APPS),
        BloatApp("com.uscc.uscclink", "USCC Link", "Account app", BloatCategory.CARRIER_APPS),
        BloatApp("com.customermobile.preload.vzw", "VZW Preload", "Verizon preload", BloatCategory.CARRIER_APPS),
        BloatApp("com.customermobile.preload.tmo", "T-Mobile Preload", "T-Mobile preload", BloatCategory.CARRIER_APPS),
        BloatApp("com.customermobile.preload.att", "AT&T Preload", "AT&T preload", BloatCategory.CARRIER_APPS),
        BloatApp("com.verizon.vzwapho", "VZWAPHO", "Verizon photo", BloatCategory.CARRIER_APPS),
        BloatApp("com.vzw.apnlib", "Verizon APN", "APN settings", BloatCategory.CARRIER_APPS)
    )

    val SOCIAL_MEDIA = listOf(
        BloatApp("com.facebook.katana", "Facebook", "Social network", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE, "Mastodon, Diaspora"),
        BloatApp("com.facebook.orca", "Messenger", "Facebook chat", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE, "Signal, Telegram"),
        BloatApp("com.facebook.appmanager", "Facebook App Manager", "FB background service", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.facebook.services", "Facebook Services", "FB services", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.facebook.system", "Facebook System", "FB system app", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.instagram.android", "Instagram", "Photo sharing", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE, "Pixelfed"),
        BloatApp("com.whatsapp", "WhatsApp", "Messaging", BloatCategory.SOCIAL_MEDIA, BloatRisk.CAUTION, "Signal, Telegram"),
        BloatApp("com.snapchat.android", "Snapchat", "Social media", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE),
        BloatApp("com.twitter.android", "Twitter/X", "Social network", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE, "Mastodon, Nitter"),
        BloatApp("com pinterest", "Pinterest", "Image sharing", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE),
        BloatApp("com.linkedin.android", "LinkedIn", "Professional network", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE),
        BloatApp("com.zhiliaoapp.musically", "TikTok", "Video sharing", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE, "Loops, PeerTube"),
        BloatApp("com.ss.android.ugc.trill", "TikTok Lite", "Video sharing", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE),
        BloatApp("com.reddit.frontpage", "Reddit", "Discussion forum", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE, "Lemmy, Kbin"),
        BloatApp("com.discord", "Discord", "Chat app", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE, "Matrix, Revolt"),
        BloatApp("org.telegram.messenger", "Telegram", "Messaging", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE),
        BloatApp("com.tencent.mm", "WeChat", "Messaging", BloatCategory.SOCIAL_MEDIA, BloatRisk.CAUTION),
        BloatApp("com.viber.voip", "Viber", "Messaging", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE, "Signal"),
        BloatApp("com.linecorp.b612.android", "B612", "Photo editor", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE),
        BloatApp("com.linecorp.line", "LINE", "Messaging", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE),
        BloatApp("com.kakao.talk", "KakaoTalk", "Messaging", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE),
        BloatApp("com.tencent.mobileqq", "QQ", "Messaging", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE),
        BloatApp("com.spotify.music", "Spotify", "Music streaming", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE, "Spotube"),
        BloatApp("com.soundcloud.android", "SoundCloud", "Music streaming", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE),
        BloatApp("com.amazon.mp3", "Amazon Music", "Music streaming", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE),
        BloatApp("com.apple.android.music", "Apple Music", "Music streaming", BloatCategory.SOCIAL_MEDIA, BloatRisk.SAFE)
    )

    val GENERIC_ADWARE = listOf(
        BloatApp("com.android.hotwordenrollment.okgoogle", "OK Google", "Voice activation", BloatCategory.ADVERTISING),
        BloatApp("com.android.hotwordenrollment.xgoogle", "XGoogle Hotword", "Voice service", BloatCategory.ADVERTISING),
        BloatApp("com.google.android.gms.location.reporter", "Location Reporter", "Location tracking", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.google.android.gms.droidguard", "DroidGuard", "SafetyNet", BloatCategory.TRACKING_SPYWARE, BloatRisk.ADVANCED),
        BloatApp("com.google.android.gms.carrierconfig", "Carrier Config", "Carrier settings", BloatCategory.CARRIER_APPS),
        BloatApp("com.google.android.gms.car", "Android Auto", "Car interface", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.android.vending.billing.InAppBillingService", "In-App Billing", "Payment service", BloatCategory.ADVERTISING),
        BloatApp("com.android.providers.partnerbookmarks", "Partner Bookmarks", "Browser bookmarks", BloatCategory.ADVERTISING),
        BloatApp("com.android.partnerbrowsercustomizations", "Browser Customization", "Browser config", BloatCategory.ADVERTISING),
        BloatApp("com.android.bookmarkprovider", "Bookmark Provider", "Bookmarks service", BloatCategory.ADVERTISING),
        BloatApp("com.android.wallpaperbackup", "Wallpaper Backup", "Wallpaper sync", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.android.managedprovisioning", "Device Owner", "Enterprise enrollment", BloatCategory.OEM_BLOATWARE, BloatRisk.ADVANCED),
        BloatApp("com.android.stk", "SIM Toolkit", "SIM app", BloatCategory.CARRIER_APPS, BloatRisk.SAFE),
        BloatApp("com.android.stk2", "SIM Toolkit 2", "SIM app", BloatCategory.CARRIER_APPS, BloatRisk.SAFE),
        BloatApp("com.android.cellbroadcastreceiver", "Emergency Alerts", "Emergency broadcast", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.android.cellbroadcastreceiver.moduleplatform", "Cell Broadcast", "Broadcast service", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.android.dreams.basic", "Basic Daydreams", "Screensaver", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.android.dreams.phototable", "Photo Screensavers", "Screensaver", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.android.dreams.wiktionary", "Wiktionary Dreams", "Screensaver", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.android.egg", "Android Easter Egg", "Easter egg game", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.android.emergency", "Emergency SOS", "Emergency info", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.android.inputdevices", "Input Devices", "Input config", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.android.pacprocessor", "PAC Processor", "Proxy config", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.android.printspooler", "Print Spooler", "Printing service", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.android.quicksearchbox", "Quick Search Box", "Search app", BloatCategory.ADVERTISING),
        BloatApp("com.android.sharedstoragebackup", "Shared Storage Backup", "Storage backup", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.android.soundpicker", "Sound Picker", "Ringtone picker", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.android.statementservice", "Statement Service", "App verification", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.android.thememanager", "Theme Manager", "Theme picker", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.android.thememanager.module", "Theme Module", "Theme service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.android.vpndialogs", "VPN Dialogs", "VPN prompts", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.android.wallpaper.livepicker", "Live Wallpaper Picker", "Live wallpapers", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.android.wallpaperpicker", "Wallpaper Picker", "Wallpaper selector", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.qualcomm.qti.ims", "IMS Service", "VoLTE service", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.qualcomm.qti.qms.service.telemetry", "Qualcomm Telemetry", "Usage tracking", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.qualcomm.location", "Qualcomm Location", "GPS service", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.qualcomm.atfwd", "AT Forward", "Modem service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.qualcomm.embms", "eMBMS", "Broadcast service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.qualcomm.qti.console", "Qualcomm Console", "Debug console", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.qualcomm.qti.poweroffalarm", "Power Off Alarm", "Alarm service", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.qualcomm.qti.auth.fidocryptoservice", "Fido Crypto", "Auth service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.qualcomm.qti.auth.sampleextauthservice", "Ext Auth", "Auth service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.qualcomm.qti.remoteSimlockAuth", "SIM Lock Auth", "SIM service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.qualcomm.uimremoteclient", "UIM Remote", "SIM client", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.qualcomm.uimremoteserver", "UIM Server", "SIM server", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.qti.qualcomm.datastatusnotification", "Data Status", "Network status", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.qti.diagservices", "Diagnostics", "Diagnostic tools", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.qti.service.colorservice", "Color Service", "Display service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.qti.snapdragon.qrd.ma", "QRD MA", "Qualcomm service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.qti.xdivert", "XDivert", "Call service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.mediatek.datamigrationapp", "MediaTek Migration", "Data transfer", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.mediatek.nlpservice", "NLP Service", "Location service", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.mediatek.batterywarning", "Battery Warning", "Battery alert", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.mediatek.autostartservice", "AutoStart", "Startup manager", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.mediatek.mtklogger", "MTK Logger", "System logging", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.mediatek.thermalengine", "Thermal Engine", "Thermal management", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.mfi", "MFI Service", "Made for iPhone", BloatCategory.OEM_BLOATWARE)
    )

    val TRACKING_SERVICES = listOf(
        BloatApp("com.google.android.gms.trustagent", "Trust Agent", "Trusted devices", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.google.android.gms.update", "GMS Update", "Service updates", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.google.android.configupdater", "Config Updater", "Remote config", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.google.android.datatransport", "Data Transport", "Data sync", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.google.android.feedback", "Feedback", "Crash reports", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.google.android.gms.licensing", "Play Licensing", "License check", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.google.android.gms.setup", "GMS Setup", "Initial setup", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.google.android.gms.ui", "GMS UI", "Service interface", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.google.android.providers.settings", "Settings Provider", "Settings sync", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.google.android.setupwizard", "Setup Wizard", "Initial configuration", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.google.android.syncadapters.bookmarks", "Bookmark Sync", "Bookmark syncing", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.google.android.apps.work.oobconfig", "Work Config", "Enterprise setup", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.samsungpassautofill", "Samsung Pass Autofill", "Auto-fill service", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.samsung.android.authservice", "Auth Service", "Authentication", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.samsungpass.setting", "Samsung Pass Settings", "Password settings", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.svoice.im", "S Voice", "Voice assistant", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.svoice", "S Voice Service", "Voice service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.SMT", "Samsung TTS", "Text-to-speech", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.storyservice", "Story Service", "Photo stories", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.aircommandmanager", "Air Command", "S Pen manager", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.sec.android.app.dexonpc", "DeX on PC", "Desktop mode", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.sec.android.app.desktoplauncher", "DeX Launcher", "Desktop interface", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.knox.containercore", "Knox Container", "Enterprise container", BloatCategory.OEM_BLOATWARE, BloatRisk.ADVANCED),
        BloatApp("com.samsung.android.knox.containeragent", "Knox Agent", "Enterprise agent", BloatCategory.OEM_BLOATWARE, BloatRisk.ADVANCED),
        BloatApp("com.samsung.knox.keychain", "Knox Keychain", "Key storage", BloatCategory.OEM_BLOATWARE, BloatRisk.ADVANCED),
        BloatApp("com.samsung.knox.securefolder", "Secure Folder", "Private folder", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.sec.knox.switcher", "Knox Switcher", "Profile switcher", BloatCategory.OEM_BLOATWARE, BloatRisk.ADVANCED),
        BloatApp("com.sec.knox.knoxsetupwizardclient", "Knox Setup", "Enterprise setup", BloatCategory.OEM_BLOATWARE, BloatRisk.ADVANCED),
        BloatApp("com.samsung.klmsagent", "KLMS Agent", "License management", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.samsung.knox.kpecore", "KPE Core", "Enterprise core", BloatCategory.OEM_BLOATWARE, BloatRisk.ADVANCED),
        BloatApp("com.samsung.knox.kpeservice", "KPE Service", "Enterprise service", BloatCategory.OEM_BLOATWARE, BloatRisk.ADVANCED),
        BloatApp("com.samsung.android.knox.attestation", "Knox Attestation", "Device verification", BloatCategory.TRACKING_SPYWARE, BloatRisk.ADVANCED),
        BloatApp("com.samsung.android.mobileservice", "Samsung Mobile Service", "Backend service", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.samsung.android.smartswitchassistant", "Smart Switch", "Device migration", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.smartmirroring", "Smart View", "Screen mirroring", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.samsung.android.app.dofviewer", "DOF Viewer", "3D viewer", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.scloud.clients", "Samsung Cloud Client", "Cloud sync", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.samsung.android.scloud.auth", "Cloud Auth", "Cloud authentication", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.samsung.android.scloud.upgrade", "Cloud Upgrade", "Storage upgrade", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.sec.android.app.samsungapps", "Galaxy Store", "Samsung app store", BloatCategory.ADVERTISING),
        BloatApp("com.sec.android.app.chromecustomizations", "Chrome Customization", "Browser config", BloatCategory.ADVERTISING),
        BloatApp("com.sec.android.app.browser", "Samsung Internet", "Web browser", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.sec.android.app.fm", "FM Radio", "Radio app", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.sec.android.app.clockpackage", "Samsung Clock", "Clock app", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.sec.android.app.voicenote", "Voice Recorder", "Audio recorder", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.sec.android.app.myfiles", "My Files", "File manager", BloatCategory.OEM_BLOATWARE, BloatRisk.SAFE),
        BloatApp("com.sec.android.app.launcher", "Samsung Home", "Home launcher", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION, "Nova Launcher"),
        BloatApp("com.sec.android.easyMover", "Smart Switch", "Data transfer", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.sec.android.easyMover.Agent", "Smart Switch Agent", "Transfer service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.sec.android.preloadinstaller", "Preload Installer", "App installer", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.sec.android.splitsound", "Split Sound", "Audio routing", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.sec.android.widgetapp.easymodecontactswidget", "Easy Mode Widget", "Accessibility widget", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.sec.android.widgetapp.samsungapps", "Galaxy Apps Widget", "Store widget", BloatCategory.ADVERTISING),
        BloatApp("com.sec.android.widgetapp.webmanual", "Web Manual Widget", "Help widget", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.sec.enterprise.mdm.services.simpin", "SIM PIN MDM", "Enterprise SIM", BloatCategory.OEM_BLOATWARE, BloatRisk.ADVANCED),
        BloatApp("com.sec.enterprise.mdm.vpn", "Enterprise VPN", "Corporate VPN", BloatCategory.OEM_BLOATWARE, BloatRisk.ADVANCED),
        BloatApp("com.sec.epdg", "ePDG", "WiFi calling", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.sec.epdgtestapp", "ePDG Test", "Testing app", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.sec.location.nsflp2", "NSF Location", "Location service", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.sec.modem.settings", "Modem Settings", "Modem config", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.sec.spp.push", "Samsung Push", "Push service", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.sec.sve", "SVE Service", "Security service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.sem.factoryapp", "Factory App", "Factory test", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.wsomacp", "OMA CP", "Provisioning", BloatCategory.CARRIER_APPS),
        BloatApp("com.wssnps", "Samsung SNPS", "Sync service", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.samsung.android.scpm", "SCPM", "Power management", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.sdm.config", "SDM Config", "Device management", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.smartfitting", "Smart Fitting", "App optimization", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.sm.devicesecurity", "Device Security", "Security service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.sm.policy", "SM Policy", "Security policy", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.spdclient", "SPD Client", "Security client", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.samsung.android.stickerplugin", "Sticker Plugin", "Sticker service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.themecenter", "Theme Center", "Theme store", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.themestore", "Theme Store", "Theme marketplace", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.udts", "UDTS", "Device tracking", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.samsung.android.universalswitch", "Universal Switch", "Accessibility", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.visioncloudagent", "Vision Cloud", "Cloud vision", BloatCategory.CLOUD_SERVICES),
        BloatApp("com.samsung.android.visionintelligence", "Vision Intelligence", "AI vision", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.wearable.app", "Galaxy Wearable", "Watch app", BloatCategory.OEM_BLOATWARE, BloatRisk.CAUTION),
        BloatApp("com.samsung.android.wearable.samsungaccessorymanager", "Accessory Manager", "Wearable service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.wifi.resources", "WiFi Resources", "WiFi config", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.android.wifi.softapwpathirdparty", "WiFi SoftAP", "Hotspot service", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.ipc.securefileutils", "Secure File Utils", "Security utils", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.ipc.securelogger", "Secure Logger", "Security logging", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.samsung.ipc.sw_logger", "SW Logger", "Software logging", BloatCategory.TRACKING_SPYWARE),
        BloatApp("com.samsung.safetyinformation", "Safety Info", "Safety info", BloatCategory.OEM_BLOATWARE),
        BloatApp("com.samsung.slsi.tetheringbcnservice", "Tethering BCN", "Hotspot beacon", BloatCategory.OEM_BLOATWARE)
    )

    fun getAllBloatware(): List<BloatApp> {
        return SAMSUNG_BLOATWARE +
                XIAOMI_BLOATWARE +
                ONEPLUS_BLOATWARE +
                HUAWEI_BLOATWARE +
                OPPO_BLOATWARE +
                VIVO_BLOATWARE +
                REALME_BLOATWARE +
                MOTOROLA_BLOATWARE +
                GOOGLE_BLOATWARE +
                CARRIER_BLOATWARE +
                SOCIAL_MEDIA +
                GENERIC_ADWARE +
                TRACKING_SERVICES
    }

    fun getByCategory(category: BloatCategory): List<BloatApp> {
        return getAllBloatware().filter { it.category == category }
    }

    fun getByManufacturer(manufacturer: String): List<BloatApp> {
        return when (manufacturer.lowercase()) {
            "samsung" -> SAMSUNG_BLOATWARE
            "xiaomi", "redmi", "poco" -> XIAOMI_BLOATWARE
            "oneplus" -> ONEPLUS_BLOATWARE
            "huawei", "honor" -> HUAWEI_BLOATWARE
            "oppo" -> OPPO_BLOATWARE
            "vivo", "iqoo" -> VIVO_BLOATWARE
            "realme" -> REALME_BLOATWARE
            "motorola", "moto" -> MOTOROLA_BLOATWARE
            "google" -> GOOGLE_BLOATWARE
            else -> emptyList()
        }
    }

    fun searchPackages(query: String): List<BloatApp> {
        val lowerQuery = query.lowercase()
        return getAllBloatware().filter {
            it.packageName.lowercase().contains(lowerQuery) ||
                    it.name.lowercase().contains(lowerQuery) ||
                    it.description.lowercase().contains(lowerQuery)
        }
    }
}
